// Package doctor implements POST /v1/doctor — the conversational plant
// diagnosis endpoint. The reply is generated by a vision LLM as strict
// structured JSON and streamed back to the app as typed SSE events, so the
// 5–15 s generation shows live progress instead of a blank spinner.
// Contract, protections and rationale: SPEC.md.
package doctor

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"
	"time"
)

const (
	// maxBody matches the nginx client_max_body_size 9M and the
	// identify/diagnose posture: the Go cap is the real limit, nginx is the
	// outer shield.
	maxBody = 9 << 20

	maxImages     = 3
	maxTextBytes  = 2 << 10
	maxHistory    = 8
	maxReplyBytes = 8 << 10
	// maxHistoryBytes sits above the sum of per-turn caps (8 × (8 KB reply +
	// 2 KB text) = 80 KB) so a maximal legal history is never truncated into
	// invalid JSON by the LimitReader.
	maxHistoryBytes = 96 << 10
)

// modelWhitelist bounds what a model override can select even in dev —
// "allow override" must never mean "spend on anything a client names".
var modelWhitelist = map[string]bool{
	"gpt-4o-mini": true,
	"gpt-4o":      true,
	"gpt-5-mini":  true,
	"gpt-5":       true,
	"grok-4.6":    true,
}

// SpendGate is the hourly budget check (ratelimit.GlobalGate). Called AFTER
// validation, right before the upstream dial — a malformed request that 400s
// early must not draw down the shared budget (same rationale as
// identify/diagnose in server.go).
type SpendGate func(http.ResponseWriter) bool

// Service carries the endpoint's configuration. Built once in main.go from
// the secrets vault; nil Service → route unregistered.
type Service struct {
	Client *Client
	// XAIClient 服务 grok-* 系（api.x.ai，OpenAI 兼容线协议）。nil = 未配
	// XAI_API_KEY，grok 选择静默回落 Model（部署不配即无 xAI 面）。
	XAIClient     *Client
	Model         string // default model (vault DOCTOR_MODEL)
	AllowOverride bool   // vault DOCTOR_ALLOW_MODEL_OVERRIDE; prod stays false
	// gpt-5 系列的思考档位（vault DOCTOR_REASONING_EFFORT；空 = low）。
	ReasoningEffort string
	// FollowupModel：第 LeadTurns+1 轮起改用的省钱档（空 = 全程 Model）。
	FollowupModel string
	// LeadTurns：主力模型负责的前几轮，默认 2。
	LeadTurns int
}

// NewService wires the streaming client. endpoint == "" → OpenAI.
func NewService(apiKey, endpoint, model string, allowOverride bool) *Service {
	// ReasoningEffort 由 main 从 vault 注入（可缺省）
	if !modelWhitelist[model] {
		if model != "" {
			log.Printf("WARN: DOCTOR_MODEL %q not in whitelist; using gpt-4o-mini", model)
		}
		model = "gpt-4o-mini"
	}
	return &Service{
		Client:        NewClient(apiKey, endpoint),
		Model:         model,
		AllowOverride: allowOverride,
	}
}

// resolveModel applies an override request against policy. Unauthorized or
// unknown overrides fall back silently to the default — a stale debug build
// must degrade, not break (SPEC §2).
// clientFor returns the upstream client for a resolved model.
// grok-* → XAIClient；其余 → OpenAI Client。
func (s *Service) clientFor(model string) *Client {
	if strings.HasPrefix(model, "grok") && s.XAIClient != nil {
		return s.XAIClient
	}
	return s.Client
}

// resolveModel picks the model for this turn.
// 档位策略（用户拍板 2026-08-13）：前 LeadTurns 轮走主力模型（看图定性 +
// 用户看着照片补充信息的关键轮），之后走 FollowupModel 省钱 —— 追问多是
// 执行确认。debug 覆盖（仅 AllowOverride 环境）仍然最高优先。
func (s *Service) resolveModel(requested string, priorTurns int) string {
	if requested != "" && s.AllowOverride && modelWhitelist[requested] {
		if strings.HasPrefix(requested, "grok") && s.XAIClient == nil {
			log.Printf("doctor: override %q needs XAI_API_KEY (absent); ignoring", requested)
		} else {
			return requested
		}
	}
	pick := s.Model
	if s.FollowupModel != "" && priorTurns >= s.LeadTurns {
		pick = s.FollowupModel
	}
	if strings.HasPrefix(pick, "grok") && s.XAIClient == nil {
		log.Printf("doctor: model %q needs XAI_API_KEY (absent); falling back to gpt-4o-mini", pick)
		return "gpt-4o-mini"
	}
	return pick
}

// Handle returns the /v1/doctor handler. Per-IP / per-device rate limits and
// the doctor-specific inflight bound are middleware in server.go; gate is the
// doctor-specific hourly budget.
func Handle(svc *Service, gate SpendGate) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		r.Body = http.MaxBytesReader(w, r.Body, maxBody)

		// Same header contract as /v1/diagnose. Middleware enforces the
		// device id in production; re-checking here keeps direct handler
		// tests honest.
		if r.Header.Get("X-App-Version") == "" {
			writeError(w, http.StatusBadRequest, "missing_app_version")
			return
		}
		deviceID := r.Header.Get("X-Device-Install-Id")
		if !isUUID(deviceID) {
			writeError(w, http.StatusBadRequest, "missing_device_id")
			return
		}

		if !strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
			writeError(w, http.StatusBadRequest, "bad_multipart")
			return
		}
		mr, err := r.MultipartReader()
		if err != nil {
			writeError(w, http.StatusBadRequest, "bad_multipart")
			return
		}

		var (
			images  [][]byte
			text    string
			history []HistoryTurn
			lang    string
			units   string
			model   string
		)
		for {
			part, perr := mr.NextPart()
			if perr == io.EOF {
				break
			}
			if perr != nil {
				if isMaxBytesErr(perr) {
					writeError(w, http.StatusRequestEntityTooLarge, "image_too_large")
					return
				}
				writeError(w, http.StatusBadRequest, "bad_multipart")
				return
			}
			switch part.FormName() {
			case "image":
				if len(images) >= maxImages {
					_ = part.Close()
					writeError(w, http.StatusBadRequest, "too_many_images")
					return
				}
				b, rerr := io.ReadAll(part)
				if rerr != nil {
					if isMaxBytesErr(rerr) {
						writeError(w, http.StatusRequestEntityTooLarge, "image_too_large")
						return
					}
					writeError(w, http.StatusBadRequest, "bad_multipart")
					return
				}
				if len(b) == 0 {
					continue
				}
				switch http.DetectContentType(b) {
				case "image/jpeg", "image/png", "image/webp":
				default:
					writeError(w, http.StatusBadRequest, "bad_image")
					return
				}
				images = append(images, b)
			case "text":
				text = readField(part, maxTextBytes)
			case "history":
				raw := readField(part, maxHistoryBytes)
				if raw != "" {
					if err := json.Unmarshal([]byte(raw), &history); err != nil ||
						len(history) > maxHistory || !historyWithinCaps(history) {
						writeError(w, http.StatusBadRequest, "bad_history")
						return
					}
				}
			case "language":
				lang = readField(part, 64)
			case "units":
				units = readField(part, 16)
			case "model":
				model = readField(part, 64)
			default:
				_, _ = io.Copy(io.Discard, part) // unknown fields ignored, part drained
			}
			_ = part.Close()
		}

		text = strings.TrimSpace(text)
		if text == "" && len(images) == 0 {
			writeError(w, http.StatusBadRequest, "empty_request")
			return
		}

		// Budget draw sits AFTER all validation (SPEC §4).
		if !gate(w) {
			return
		}

		resolved := svc.resolveModel(model, len(history))

		flusher, ok := w.(http.Flusher)
		if !ok {
			// Impossible under net/http; keeps the contract explicit.
			writeError(w, http.StatusInternalServerError, "no_stream")
			return
		}

		// main.go's http.Server has WriteTimeout ≈ 35 s (sized for
		// identify/diagnose). That deadline covers the WHOLE response write,
		// so an SSE stream would be severed mid-generation at 35 s. Extend
		// the write deadline for THIS connection only; every other endpoint
		// keeps the strict global timeout. Best-effort: recorders in tests
		// don't support it, and a failure here just means the old deadline.
		deadline := time.Now().Add(streamTimeout + 10*time.Second)
		_ = http.NewResponseController(w).SetWriteDeadline(deadline)

		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		// nginx honors this per-response; the vhost location additionally
		// sets proxy_buffering off (SPEC §3 — belt and suspenders).
		w.Header().Set("X-Accel-Buffering", "no")
		w.WriteHeader(http.StatusOK)
		flusher.Flush()
		out := sseWriter{w: w, f: flusher}

		ctx, cancel := context.WithTimeout(r.Context(), streamTimeout)
		defer cancel()

		obsCount := 0
		reply, usage, err := svc.clientFor(resolved).Stream(ctx, StreamRequest{
			ReasoningEffort: svc.ReasoningEffort,
			Model:           resolved,
			Language:        lang,
			Units:           units,
			History:         history,
			UserText:        text,
			Images:          images,
		}, func(index int, s string) {
			obsCount++
			out.event("observation", map[string]any{"index": index, "text": s})
		})

		ms := time.Since(start).Milliseconds()
		if err != nil {
			code := "bad_upstream"
			switch {
			case errors.Is(err, ErrUpstreamTimeout):
				code = "upstream_timeout"
			case errors.Is(err, ErrBadReply):
				code = "bad_reply"
			}
			// Client went away → nothing to write, and the cancelled context
			// already stopped the paid upstream call.
			if r.Context().Err() == nil {
				out.event("error", map[string]any{"code": code})
			}
			log.Printf("doctor: device=%s ms=%d model=%s obs=%d err=%v", deviceID, ms, resolved, obsCount, err)
			return
		}

		if usage != nil {
			out.event("usage", usage)
		}
		out.eventRaw("reply", json.RawMessage(reply))
		in, outTok := 0, 0
		if usage != nil {
			in, outTok = usage.PromptTokens, usage.CompletionTokens
		}
		log.Printf("doctor: device=%s ms=%d model=%s obs=%d in=%d out=%d imgs=%d turns=%d",
			deviceID, ms, resolved, obsCount, in, outTok, len(images), len(history))
	}
}

func historyWithinCaps(turns []HistoryTurn) bool {
	for _, t := range turns {
		if len(t.User) > maxTextBytes || len(t.Reply) > maxReplyBytes {
			return false
		}
		if len(t.Reply) > 0 && !json.Valid(t.Reply) {
			return false
		}
	}
	return true
}

func readField(r io.Reader, limit int64) string {
	b, _ := io.ReadAll(io.LimitReader(r, limit))
	return string(b)
}

// ---- SSE plumbing ----

// sseWriter serializes one event per call. json.Marshal never emits raw
// newlines (they are escaped), so `data:` is always a single line.
type sseWriter struct {
	w http.ResponseWriter
	f http.Flusher
}

func (s sseWriter) event(name string, v any) {
	b, err := json.Marshal(v)
	if err != nil {
		return
	}
	s.write(name, b)
}

func (s sseWriter) eventRaw(name string, raw json.RawMessage) {
	// Compact defensively: the reply came from upstream and pretty-printed
	// JSON would carry raw newlines, which break SSE framing.
	var buf bytes.Buffer
	if err := json.Compact(&buf, raw); err != nil {
		return
	}
	s.write(name, buf.Bytes())
}

func (s sseWriter) write(name string, data []byte) {
	fmt.Fprintf(s.w, "event: %s\ndata: %s\n\n", name, data)
	s.f.Flush()
}

// ---- small local copies of proxy helpers (unexported there) ----

type errorResponse struct {
	Error string `json:"error"`
}

func writeError(w http.ResponseWriter, status int, code string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(errorResponse{Error: code})
}

func isMaxBytesErr(err error) bool {
	var mbe *http.MaxBytesError
	return errors.As(err, &mbe)
}

// isUUID accepts RFC 4122 canonical form (36 chars, dashes at 8/13/18/23),
// hex case-insensitive — same acceptance as the proxy handlers.
func isUUID(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch i {
		case 8, 13, 18, 23:
			if c != '-' {
				return false
			}
		default:
			isHex := (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')
			if !isHex {
				return false
			}
		}
	}
	return true
}

// ModelAllowed exposes the whitelist for config validation in main.
func ModelAllowed(m string) bool { return modelWhitelist[m] }
