package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/yaochen1125/yardmate-api/attest"
	"github.com/yaochen1125/yardmate-api/attest/testkit"
	"github.com/yaochen1125/yardmate-api/ratelimit"
	"github.com/yaochen1125/yardmate-api/secrets"
)

// buildE2EServer wires a Server using a test root pool generated by testkit,
// so the full attestation → assertion → secrets flow runs in-process.
func buildE2EServer(t *testing.T, ipLimit int) (*Server, *testkit.Issuer) {
	t.Helper()
	issuer := testkit.NewIssuer(t, "TEAM12345.com.example.test")

	dir := t.TempDir()
	store, err := attest.OpenStore(filepath.Join(dir, "test.db"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = store.Close() })

	verifier, err := attest.New(attest.Options{
		AppID:    issuer.AppID,
		Store:    store,
		RootPool: issuer.RootPool,
	})
	if err != nil {
		t.Fatal(err)
	}

	vault, err := secrets.Parse(strings.NewReader(
		"OPENAI_API_KEY=e2e-openai\nPLANT_ID_API_KEY=e2e-plantid\n",
	))
	if err != nil {
		t.Fatal(err)
	}

	lim := ratelimit.New(ipLimit, time.Hour, 1000, 24*time.Hour, 1000, time.Hour)
	return newServer(verifier, vault, lim, nil, nil, nil, nil), issuer
}

func postJSON(t *testing.T, s *Server, path string, body any) *httptest.ResponseRecorder {
	t.Helper()
	b, _ := json.Marshal(body)
	req := httptest.NewRequest("POST", path, bytes.NewReader(b))
	req.Header.Set("Content-Type", "application/json")
	req.RemoteAddr = "127.0.0.1:1234"
	rr := httptest.NewRecorder()
	s.ServeHTTP(rr, req)
	return rr
}

// TestE2E_HappyPath walks the entire iOS → server protocol:
//  1. POST /v1/attest/challenge       → server hands out a challenge
//  2. iOS mints attestation           → testkit.MintAttestation
//  3. POST /v1/attest/register         → server stores the credential
//  4. POST /v1/secrets/challenge       → server hands out a fresh challenge
//  5. iOS mints assertion              → testkit.MintAssertion
//  6. POST /v1/app-secrets            → server vends OPENAI_API_KEY + PLANT_ID_API_KEY
func TestE2E_HappyPath(t *testing.T) {
	s, issuer := buildE2EServer(t, 1000)

	// 1. attest challenge
	rr := postJSON(t, s, "/v1/attest/challenge", map[string]string{})
	if rr.Code != http.StatusOK {
		t.Fatalf("attest challenge: code %d body %s", rr.Code, rr.Body)
	}
	var attChal challengeResponse
	if err := json.NewDecoder(rr.Body).Decode(&attChal); err != nil {
		t.Fatal(err)
	}
	challenge, err := base64.StdEncoding.DecodeString(attChal.Challenge)
	if err != nil {
		t.Fatalf("decode challenge: %v", err)
	}

	// 2-3. attestation + register
	keyID, attCBOR := issuer.MintAttestation(t, testkit.AttestParams{Challenge: challenge})
	rr = postJSON(t, s, "/v1/attest/register", map[string]string{
		"keyID":       base64.StdEncoding.EncodeToString(keyID),
		"attestation": base64.StdEncoding.EncodeToString(attCBOR),
		"challenge":   attChal.Challenge,
	})
	if rr.Code != http.StatusOK {
		t.Fatalf("register: code %d body %s", rr.Code, rr.Body)
	}

	// 4. secrets challenge
	rr = postJSON(t, s, "/v1/secrets/challenge", map[string]string{})
	if rr.Code != http.StatusOK {
		t.Fatalf("secrets challenge: code %d body %s", rr.Code, rr.Body)
	}
	var secChal challengeResponse
	json.NewDecoder(rr.Body).Decode(&secChal)
	secChallenge, _ := base64.StdEncoding.DecodeString(secChal.Challenge)

	// 5-6. assertion + app-secrets vending
	assCBOR := issuer.MintAssertion(t, testkit.AssertionParams{
		Counter:   1,
		Challenge: secChallenge,
	})
	rr = postJSON(t, s, "/v1/app-secrets", map[string]string{
		"keyID":     base64.StdEncoding.EncodeToString(keyID),
		"assertion": base64.StdEncoding.EncodeToString(assCBOR),
		"challenge": secChal.Challenge,
	})
	if rr.Code != http.StatusOK {
		t.Fatalf("app-secrets: code %d body %s", rr.Code, rr.Body)
	}
	var sec map[string]string
	json.NewDecoder(rr.Body).Decode(&sec)
	if sec["openai_api_key"] != "e2e-openai" {
		t.Errorf("openai = %q, want e2e-openai", sec["openai_api_key"])
	}
	if sec["plant_id_api_key"] != "e2e-plantid" {
		t.Errorf("plantid = %q, want e2e-plantid", sec["plant_id_api_key"])
	}
}

// TestE2E_SecondAssertionWithIncrementedCounterWorks confirms a registered
// keyID can vend secrets repeatedly as long as the counter grows.
func TestE2E_RepeatedAssertions(t *testing.T) {
	s, issuer := buildE2EServer(t, 1000)

	// Register first.
	rr := postJSON(t, s, "/v1/attest/challenge", map[string]string{})
	var attChal challengeResponse
	json.NewDecoder(rr.Body).Decode(&attChal)
	ch, _ := base64.StdEncoding.DecodeString(attChal.Challenge)
	keyID, attCBOR := issuer.MintAttestation(t, testkit.AttestParams{Challenge: ch})
	rr = postJSON(t, s, "/v1/attest/register", map[string]string{
		"keyID":       base64.StdEncoding.EncodeToString(keyID),
		"attestation": base64.StdEncoding.EncodeToString(attCBOR),
		"challenge":   attChal.Challenge,
	})
	if rr.Code != 200 {
		t.Fatalf("register: %s", rr.Body)
	}

	for counter := uint32(1); counter <= 3; counter++ {
		rr = postJSON(t, s, "/v1/secrets/challenge", map[string]string{})
		var sc challengeResponse
		json.NewDecoder(rr.Body).Decode(&sc)
		scBytes, _ := base64.StdEncoding.DecodeString(sc.Challenge)
		ass := issuer.MintAssertion(t, testkit.AssertionParams{Counter: counter, Challenge: scBytes})
		rr = postJSON(t, s, "/v1/app-secrets", map[string]string{
			"keyID":     base64.StdEncoding.EncodeToString(keyID),
			"assertion": base64.StdEncoding.EncodeToString(ass),
			"challenge": sc.Challenge,
		})
		if rr.Code != http.StatusOK {
			t.Fatalf("counter=%d: code %d body %s", counter, rr.Code, rr.Body)
		}
	}
}

// TestE2E_Concurrent_RateLimitTriggers fires 100 concurrent requests from
// one IP against a 10-request-per-hour bucket. Equivalent to
// `hey -c 100 -n 100 -m POST http://server/v1/attest/challenge` (see
// deploy/README — but in-process so it's CI-friendly).
//
// Bucket.Allow is mutex-protected, so the outcome is exact: 10 allowed, 90 denied.
func TestE2E_Concurrent_RateLimitTriggers(t *testing.T) {
	s, _ := buildE2EServer(t, 10) // 10 req/h per IP

	const N = 100
	codes := make([]int, N)
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			req := httptest.NewRequest("POST", "/v1/attest/challenge", strings.NewReader("{}"))
			req.RemoteAddr = "10.99.99.99:0" // same IP for all → shared bucket
			req.Header.Set("Content-Type", "application/json")
			rr := httptest.NewRecorder()
			s.ServeHTTP(rr, req)
			codes[idx] = rr.Code
		}(i)
	}
	wg.Wait()

	var n200, n429, nOther int
	var retryAfterSeen bool
	for i, c := range codes {
		switch c {
		case http.StatusOK:
			n200++
		case http.StatusTooManyRequests:
			n429++
			_ = i
			retryAfterSeen = true
		default:
			nOther++
		}
	}
	if n200 != 10 {
		t.Errorf("200 count = %d, want 10 (the bucket limit)", n200)
	}
	if n429 != 90 {
		t.Errorf("429 count = %d, want 90", n429)
	}
	if nOther != 0 {
		t.Errorf("unexpected status codes: %d non-200/429", nOther)
	}
	if !retryAfterSeen {
		t.Error("expected at least one 429 response")
	}
}

// TestE2E_PerKeyIDLimit_AfterVerify confirms per-keyID rate limit kicks in
// only after a successful assertion verify, and returns 429 with the
// keyID-specific tag.
func TestE2E_PerKeyIDLimit(t *testing.T) {
	issuer := testkit.NewIssuer(t, "TEAM.bundle")
	dir := t.TempDir()
	store, _ := attest.OpenStore(filepath.Join(dir, "test.db"))
	t.Cleanup(func() { _ = store.Close() })
	verifier, _ := attest.New(attest.Options{
		AppID:    issuer.AppID,
		Store:    store,
		RootPool: issuer.RootPool,
	})
	vault, _ := secrets.Parse(strings.NewReader("OPENAI_API_KEY=k\nPLANT_ID_API_KEY=p\n"))
	// Generous per-IP, tight per-keyID (2 per 24h), generous per-device.
	lim := ratelimit.New(1000, time.Hour, 2, 24*time.Hour, 1000, time.Hour)
	s := newServer(verifier, vault, lim, nil, nil, nil, nil)

	// Register.
	rr := postJSON(t, s, "/v1/attest/challenge", map[string]string{})
	var attChal challengeResponse
	json.NewDecoder(rr.Body).Decode(&attChal)
	ch, _ := base64.StdEncoding.DecodeString(attChal.Challenge)
	keyID, attCBOR := issuer.MintAttestation(t, testkit.AttestParams{Challenge: ch})
	rr = postJSON(t, s, "/v1/attest/register", map[string]string{
		"keyID":       base64.StdEncoding.EncodeToString(keyID),
		"attestation": base64.StdEncoding.EncodeToString(attCBOR),
		"challenge":   attChal.Challenge,
	})
	if rr.Code != 200 {
		t.Fatalf("register: %s", rr.Body)
	}

	hit := func(counter uint32) (int, string) {
		rr := postJSON(t, s, "/v1/secrets/challenge", map[string]string{})
		var sc challengeResponse
		json.NewDecoder(rr.Body).Decode(&sc)
		scBytes, _ := base64.StdEncoding.DecodeString(sc.Challenge)
		ass := issuer.MintAssertion(t, testkit.AssertionParams{Counter: counter, Challenge: scBytes})
		rr2 := postJSON(t, s, "/v1/app-secrets", map[string]string{
			"keyID":     base64.StdEncoding.EncodeToString(keyID),
			"assertion": base64.StdEncoding.EncodeToString(ass),
			"challenge": sc.Challenge,
		})
		var resp errorResponse
		if rr2.Header().Get("Content-Type") == "application/json" {
			// best-effort decode for error tag
			_ = json.NewDecoder(rr2.Body).Decode(&resp)
		}
		return rr2.Code, resp.Error
	}

	if c, _ := hit(1); c != 200 {
		t.Errorf("1st app-secrets = %d, want 200", c)
	}
	if c, _ := hit(2); c != 200 {
		t.Errorf("2nd app-secrets = %d, want 200", c)
	}
	c, errTag := hit(3)
	if c != http.StatusTooManyRequests {
		t.Errorf("3rd app-secrets = %d, want 429", c)
	}
	if errTag != "rate_limit_keyid" {
		t.Errorf("error tag = %q, want rate_limit_keyid", errTag)
	}
}
